#!/bin/sh

mkdir -p $INPUT_OUTPUT_DIR
KEYSTORE_OUTPUT="$INPUT_OUTPUT_DIR/$INPUT_KEYSTORE_NAME"

echo "$INPUT_ENCODED_KEYSTORE" | base64 -d > $KEYSTORE_OUTPUT || exit 1

PROPS="$INPUT_OUTPUT_DIR/$INPUT_PROPERTIES_NAME"
echo "keystore=$INPUT_KEYSTORE_NAME" > $PROPS
echo "keystore_password=$INPUT_KEYSTORE_PASSWORD" >> $PROPS
echo "alias=$INPUT_KEY_ALIAS" >> $PROPS
echo "alias_password=$INPUT_KEY_ALIAS_PASSWORD" >> $PROPS